Bank2/ViewModels/ShowAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bank2.ViewModels
{
    public class ShowAccountViewModel
    {
        public string Fornamn { get; set; }
        public string Efternamn { get; set; }
        public string AccountNo { get; set; }
        public string AccountType { get; set; }
        public float Saldo { get; set; }

    }
}

Bank2/ViewModels/ShowAccountsForUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bank2.ViewModels
{
    public class ShowAccountsForUserAccountViewModel
    {
        public string AccountNo { get; set; }
        public string Text { get; set; }
    }

    public class ShowAccountsForUserViewModel
    {

        public ShowAccountsForUserViewModel()
        {
            Accounts = new List<ShowAccountsForUserAccountViewModel>();
        }
        public string Fornamn { get; set; }
        public string Efternamn { get; set; }
        public List<ShowAccountsForUserAccountViewModel> Accounts{ get; set; }
    }
}

Bank2/ViewModels/ShowUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bank2.ViewModels
{
    public class ShowUserViewModel
    {
        public string Fornamn { get; set; }
        public string Efternamn { get; set; }
        public int AntalKonton { get; set; }
        public float TotalSumma { get; set; }
        public int Id { get; set; }
    }
}

Bank2/Controllers/BankController.cs
using Bank2.Models;
using Bank2.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bank2.Controllers
{
    public class BankController : Controller
    {
        public ActionResult SaveAccount(EditAccountViewModel modified)
        {
            int id = modified.Id;
            var dbContext = new DBContext();
            var userModel = dbContext.GetUser(id);
            userModel.BirthYear = modified.Birthyear;
            userModel.FirstName = modified.Fornamn;
            userModel.LastName = modified.Efternamn;
            userModel.City = modified.City;

            return View("NewAccount");
        }
        public ActionResult SaveNewAccount(EditAccountViewModel user)
        {
            if(user.Birthyear < 1900)
            {
                return View("NewAccount", user);
            }

            //Allt OK
            var dbContext = new DBContext();
            //spara!!

            return View();
        }

        public ActionResult NewAccount()
        {
            var model = new EditAccountViewModel();
            return View(model);
        }

        public ActionResult EditUser(int id)
        {
            var dbContext = new DBContext();
            var user = dbContext.GetUser(id);
            var model = new EditAccountViewModel
            {
                Birthyear = user.BirthYear,
                City = user.City,
                Efternamn = user.LastName,
                Fornamn = user.FirstName,
                Id = user.Id
            };
            return View(model);
        }


        // GET: Bank
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowAccountsForUser(int id)
        {
            var dbContext = new DBContext();
            var user = dbContext.GetUser(id);
            var viewModel = new ShowAccountsForUserViewModel();
            viewModel.Fornamn = user.FirstName;
            viewModel.Efternamn = user.LastName;
            foreach(var account in user.Accounts)
            {
                var accountViewModel = new ShowAccountsForUserAccountViewModel();
                accountViewModel.AccountNo = account.AccountNumber;
                if (account.Type == Account.AccountType.Savings)
                    accountViewModel.Text = "Sparkonto";
                if (account.Type == Account.AccountType.Transaction)
                    accountViewModel.Text = "Transaktionskonto";
                viewModel.Accounts.Add(accountViewModel);
            }
            return View(viewModel);
        }

        public ActionResult ShowAccount(string accountNo)
        {
            var dbContext = new DBContext();
            foreach (var user in dbContext.GetAllUsers())
            {
                var account = user.Accounts.FirstOrDefault(r => r.AccountNumber == accountNo);
                if(account != null)
                {
                    var viewModel = new ShowAccountViewModel
                    {
                        AccountNo = account.AccountNumber,
                        Efternamn = user.LastName,
                        Fornamn = user.FirstName,
                        Saldo = account.Balance
                    };
                    if (account.Type == Account.AccountType.Savings)
                        viewModel.AccountType = "Sparkonto";
                    if (account.Type == Account.AccountType.Transaction)
                        viewModel.AccountType = "Transaktionskonto";
                    return View(viewModel);
                }
            }
            return null;
        }

        public ActionResult ShowUser(int id)
        {
            var dbContext = new DBContext();
            var user = dbContext.GetUser(id);
            var showUserViewModel = new ShowUserViewModel
            {
                Efternamn = user.LastName,
                Fornamn = user.FirstName,
                AntalKonton = user.Accounts.Count(),
                TotalSumma = user.Accounts.Sum(r => r.Balance),
                Id = user.Id
            };

            return View(showUserViewModel);
        }




    }
}

Bank2/Views/Bank/EditUser.cshtml
@model Bank2.ViewModels.EditAccountViewModel
@{
    ViewBag.Title = "Edit user";
}

@using (Html.BeginForm("SaveAccount", "Bank", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)

    @Html.LabelFor(m => m.Fornamn)
    @Html.TextBoxFor(m => m.Fornamn)

    @Html.LabelFor(m => m.Efternamn)
    @Html.TextBoxFor(m => m.Efternamn)

    @Html.LabelFor(m => m.City)
    @Html.TextBoxFor(m => m.City)

    @Html.LabelFor(m => m.Birthyear)
    @Html.TextBoxFor(m => m.Birthyear)

    <input type="submit" value="Spara" />
}

Bank2/Views/Bank/NewAccount.cshtml
@model Bank2.ViewModels.EditAccountViewModel
@{
    ViewBag.Title = "NewAccount";
}

@using (Html.BeginForm("SaveNewAccount", "Bank", FormMethod.Post))
{
    @Html.LabelFor(m => m.Fornamn)
    @Html.TextBoxFor(m => m.Fornamn)

    @Html.LabelFor(m => m.Efternamn)
    @Html.TextBoxFor(m => m.Efternamn)

    @Html.LabelFor(m => m.City)
    @Html.TextBoxFor(m => m.City)

    @Html.LabelFor(m => m.Birthyear)
    @Html.TextBoxFor(m => m.Birthyear)

    <input type="submit" value="Spara" />
}

Bank2/Views/Bank/SaveNewAccount.cshtml
@{
    ViewBag.Title = "SaveNewAccount";
}

<h2>Konto skapat</h2>

Bank2/Views/Bank/ShowAccount.cshtml
@model  Bank2.ViewModels.ShowAccountViewModel

@{
    ViewBag.Title = "Show an account";
}
Ditt konto @Model.Fornamn @Model.Efternamn
med kontonummer @Model.AccountNo av typen @Model.AccountType
har saldo @Model.Saldo

Bank2/Views/Bank/ShowAccountsForUser.cshtml
@model  Bank2.ViewModels.ShowAccountsForUserViewModel

@{
    ViewBag.Title = "User accounts";
}
<h2>Här är dina konton @Model.Fornamn @Model.Efternamn</h2>


<ul>
    @foreach (var account in Model.Accounts)
    {
    <li>
        
        @Html.ActionLink(linkText: account.AccountNo, 
       actionName: "ShowAccount", 
       routeValues: new { accountNo = account.AccountNo })
           - @account.Text
    </li>
    }
</ul>

Bank2/Views/Bank/ShowUser.cshtml
@model  Bank2.ViewModels.ShowUserViewModel

@{
    ViewBag.Title = "User page";
}
<h2>Välkommen @Model.Fornamn @Model.Efternamn</h2>
<h3>Du har @Model.AntalKonton konton med totalt @Model.TotalSumma kr</h3>


Klicka här för att se @Html.ActionLink(linkText: "konton", 
                     actionName: "ShowAccountsForUser",
                    routeValues: new { id = Model.Id })